version: '3.8'

services:
  blockless-node:
    image: ghcr.io/blocklessnetwork/b7s:v0.6.2
    platform: linux/amd64
    environment:
      - NODE_ROLE=worker
      - BOOT_NODES=/ip4/146.190.197.136/tcp/31783/p2p/12D3KooWMUFNmnPBEZY5y7qqB8F6eVEzfPXG7KAd1v1FV1Q44A6d,/ip4/209.38.5.92/tcp/30564/p2p/12D3KooWK2qKNvmuYeQ7TFSkja8wqgSdvpfEYKgqkvRSf1GtpHEN
    volumes:
      - /home/grass/keys:/app/keys
      - /home/grass/db_path:/app/db
    ports:
      - "9527:9527"
    restart: always
    container_name: blockless-node
